AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TetAlexLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tet-alexa
      Runtime: go1.x
      CodeUri: ./deploy/tet-alexa.zip
      Environment:
        Variables: 
          S3_BUCKET: tet_alexa_lambda
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill